### ISSUE TITLE
Issues with TestContext being initialized outside the assembly

### ISSUE THREAD

**Issue by iammrburman** [vivrichards600/AutomatedVisualTesting#2]
As TestContext is initialised in the assembly it runs once before any testing this means that all tests ran within the same testing session even if they are in different test classes all use the same TestContext if the test fails it will show as passed if the previous test passed.

It appears the only way to get around this is to manually run one test at a time.

It may be worthwhile initalising TestClass within the UITestBindingBase TestInitialize method rather than the seperate InitializeTestContext TestClass.

Hope that makes sense 
Regards

Brett

**Comment by vivrichards600** [comment]
Changed implementation for examples of framework.
