### ISSUE TITLE
Images not complete in width with responsive web pages

### ISSUE THREAD

**Issue by LasseHifi** [vivrichards600/AutomatedVisualTesting#3]
If taking a snapshot of responsive web pages in seems that not the full width is present in the image. 
See attached image (at the right side of the page. Text is cropped)

![2018-03-15t22-25-36-actualimage](https://user-images.githubusercontent.com/35871385/37510020-04dfdae8-28fa-11e8-94c5-8304ad4acdd3.png)

**Comment by vivrichards600** [comment]
Hello - would you be able to give me the link and send me the html/css for that page so I can try to work out what is happening? Thanks, Viv.

**Comment by vivrichards600** [comment]
Unable to reproduce, please can you pull the latest changes to the framework and try again?

**Comment by vivrichards600** [comment]
No response so closing ticket.
